name: CI

on:
  push:
  pull_request:

jobs:
  lint-and-smoke:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python -m pip install black flake8

      - name: Lint (black)
        run: black --check .

      - name: Lint (flake8)
        run: flake8 .

      - name: Smoke test
        run: |
          if [ -f energy_cli.py ]; then
            python energy_cli.py --help || true
          else
            python - <<'PY'
            print("smoke: repo present; notebooks and src scaffolds exist.") PY
          fi
